# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/SSD_CONSTR.xdc

# Block Designs: bd/MY_SSD/MY_SSD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD || ORIG_REF_NAME==MY_SSD} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_processing_system7_0_0/MY_SSD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_processing_system7_0_0 || ORIG_REF_NAME==MY_SSD_processing_system7_0_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_ps7_0_axi_periph_0/MY_SSD_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_ps7_0_axi_periph_0 || ORIG_REF_NAME==MY_SSD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_rst_ps7_0_50M_0/MY_SSD_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_rst_ps7_0_50M_0 || ORIG_REF_NAME==MY_SSD_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_MY_SSD_0_0/MY_SSD_MY_SSD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_MY_SSD_0_0 || ORIG_REF_NAME==MY_SSD_MY_SSD_0_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_xbar_0/MY_SSD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_xbar_0 || ORIG_REF_NAME==MY_SSD_xbar_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_axi_gpio_0_0/MY_SSD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_axi_gpio_0_0 || ORIG_REF_NAME==MY_SSD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MY_SSD/ip/MY_SSD_auto_pc_0/MY_SSD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MY_SSD_auto_pc_0 || ORIG_REF_NAME==MY_SSD_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/malik/Documents/ECE_520_PROJECTS/FINAL/FINAL.gen/sources_1/bd/MY_SSD/MY_SSD_ooc.xdc
