# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/FINAL/FINAL.srcs/sources_1/bd/MY_SSD/ip/MY_SSD_processing_system7_0_0/MY_SSD_processing_system7_0_0.xci
# IP: The module: 'MY_SSD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/malik/Documents/ECE_520_PROJECTS/FINAL/FINAL.gen/sources_1/bd/MY_SSD/ip/MY_SSD_processing_system7_0_0/MY_SSD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MY_SSD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/malik/Documents/ECE_520_PROJECTS/FINAL/FINAL.srcs/sources_1/bd/MY_SSD/ip/MY_SSD_processing_system7_0_0/MY_SSD_processing_system7_0_0.xci
# IP: The module: 'MY_SSD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/malik/Documents/ECE_520_PROJECTS/FINAL/FINAL.gen/sources_1/bd/MY_SSD/ip/MY_SSD_processing_system7_0_0/MY_SSD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MY_SSD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
